"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''$directory$git_branch$git_commit$git_status$git_state
$character'''

right_format = '''$dotnet$golang$nodejs$rust$zig'''

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[directory]
style = 'yellow'
format = '[  $path]($style)[$read_only]($read_only_style) '
truncation_length = 5
truncate_to_repo = false

[username]
style_root = 'red'
style_user = 'cyan'
show_always = true

[git_branch]
style = 'green'
symbol = ' '

[git_commit]
style = 'purple'
format = '[\[$hash\]]($style)[$tag](yellow) '
commit_hash_length = 6
tag_disabled = false
tag_symbol = '  '
only_detached = false

[git_state]
style = 'cyan'
format = '[\[$state($progress_current/$progress_total)\]]($style) '

[git_status]
style = ''
format = '[$ahead_behind$modified$deleted$renamed$untracked]($style)'
conflicted = '[ $count](red) '
ahead = '[ $count](blue) '
behind = '[ $count](blue) '
diverged = '[ $ahead_count  $behind_count](blue) '
up_to_date = '[ ](green) '
untracked = '[ $count](blue) '
stashed = ''
modified = '[ $count](cyan) '
staged = ''
renamed = '[ $count](yellow) '
deleted = '[ $count](red) '
typechanged = ''

[dotnet]
style = 'blue'
symbol = ' '
detect_extensions = ['sln', 'csproj', 'fsproj', 'xproj']

[golang]
style = 'cyan'
symbol = ' '

[nodejs]
style = 'green'
symbol = ' '

[rust]
style = 'red'
symbol = ' '

[zig]
style = 'yellow'
symbol = ' '
